### ISSUE TITLE
correction

### ISSUE THREAD

**Issue by TimvanMeijel** [UW-Advanced-Robotics-Lab/uwarl-robot_configs#28]
See the link for the exact location for the correction:
https://github.com/UW-Advanced-Robotics-Lab/uwarl-robot_configs/tree/waterloo_steel/universal/ros1/main#2--unified-development-construction--local-pc--summit--wam-melodicnoetic 

correction: src_ws should be changed to source_ws in the build part

**Comment by jaku-jaku** [comment]
@TimvanMeijel , you can merge the fix to main 📦
